# Gambas Action File 3.0

{ Actions
  { Action Agregar
    Text = ""
    Picture = "icon:/16/ok"
  }
  { Action Borrar
    Text = ""
    Picture = "icon:/16/halt"
  }
  { Action Editar
    Text = ""
    Picture = "icon:/16/pen"
  }
}

